#!/usr/bin/env python3
"""
AGENT.md card validator + documentation generator (CARDS_SPEC.md §Auto-generation).

Walks agents/**/AGENT.md, validates each card against the spec, and regenerates
the derived documents that must never be hand-authored (they drift):

    agents/generated/HANDOFFS.md                 — Receives/Passes/Human-gate DAG
    agents/generated/CONTRACTS.md                — Inputs/Outputs per agent
    agents/generated/INFRASTRUCTURE_REQUIREMENTS.md — tool/MCP usage across agents
    agents/generated/CAPABILITY_MATRIX.md        — skills x agents
    agents/generated/SKILLS_INVENTORY.md         — skill -> agents
    agents/generated/GATES_INVENTORY.md          — gate -> agents (Human gate entries)
    agents/generated/topology.mmd                — Mermaid handoff graph

Generated files carry an AUTO-GENERATED header and live under agents/generated/
so the hand-authored docs/architecture/GATES.md is never clobbered.

Usage:
    python tools/generate_docs.py            # validate + (re)generate
    python tools/generate_docs.py --check    # validate only; exit 1 on hard errors

Stdlib only. Validation rules follow CARDS_SPEC.md §Validation Rules.
"""
from __future__ import annotations

import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
AGENTS_DIR = REPO_ROOT / "agents"
OUT_DIR = AGENTS_DIR / "generated"

SEMVER = re.compile(r"^\d+\.\d+\.\d+$")
AUTOGEN = "<!-- AUTO-GENERATED by tools/generate_docs.py — do not edit by hand. Run `make generate-docs`. -->\n\n"

REQUIRED_SECTIONS = [
    "Purpose", "Inputs", "Outputs / Artifacts", "Handoffs",
    "Behavioral Constraints", "Failure Modes & Recovery", "Evaluation Criteria",
]


# ── Parsing ──────────────────────────────────────────────────────────────────

@dataclass
class Card:
    path: Path
    dir_name: str
    team: str
    fm: dict
    sections: dict  # heading -> body text
    errors: list = field(default_factory=list)
    warnings: list = field(default_factory=list)

    @property
    def name(self) -> str:
        return self.fm.get("name", "")


def _parse_frontmatter(text: str) -> tuple[dict, str]:
    """Split a card into (frontmatter dict, body). Minimal YAML — scalars + [a, b] lists."""
    if not text.startswith("---"):
        return {}, text
    parts = text.split("---", 2)
    if len(parts) < 3:
        return {}, text
    raw, body = parts[1], parts[2]
    fm: dict = {}
    for line in raw.splitlines():
        line = line.rstrip()
        if not line or line.lstrip().startswith("#") or ":" not in line:
            continue
        key, _, val = line.partition(":")
        key, val = key.strip(), val.strip()
        if val.startswith("[") and val.endswith("]"):
            inner = val[1:-1].strip()
            fm[key] = [v.strip().strip('"').strip("'") for v in inner.split(",") if v.strip()] if inner else []
        else:
            fm[key] = val.strip('"').strip("'")
    return fm, body


def _split_sections(body: str) -> dict:
    sections: dict = {}
    current = None
    buf: list = []
    for line in body.splitlines():
        m = re.match(r"^##\s+(.*?)\s*$", line)
        if m:
            if current is not None:
                sections[current] = "\n".join(buf).strip()
            current = m.group(1).strip()
            buf = []
        elif current is not None:
            buf.append(line)
    if current is not None:
        sections[current] = "\n".join(buf).strip()
    return sections


def load_cards() -> list[Card]:
    cards: list[Card] = []
    for path in sorted(AGENTS_DIR.glob("*/*/AGENT.md")):
        fm, body = _parse_frontmatter(path.read_text())
        cards.append(Card(
            path=path,
            dir_name=path.parent.name,
            team=path.parent.parent.name,
            fm=fm,
            sections=_split_sections(body),
        ))
    return cards


# ── Validation (CARDS_SPEC.md §Validation Rules) ─────────────────────────────

def _table_field(text: str) -> str:
    return text  # placeholder for symmetry; tables parsed in generators


def validate(card: Card) -> None:
    fm, s = card.fm, card.sections
    status, trigger = fm.get("status"), fm.get("trigger")
    # Completeness is strict for active (primary) agents; advisory for not-yet-active
    # (conditional/deferred Tier-2) agents — they are incomplete by design.
    active = status == "primary"
    completeness = card.errors if active else card.warnings

    # ── Frontmatter rules — errors for ALL cards ──
    # 1. name / team match directory
    if fm.get("name") != card.dir_name:
        card.errors.append(f"name '{fm.get('name')}' != directory '{card.dir_name}'")
    if fm.get("team") != card.team:
        card.errors.append(f"team '{fm.get('team')}' != directory '{card.team}'")
    # 2. semver
    if not SEMVER.match(str(fm.get("version", ""))):
        card.errors.append(f"version '{fm.get('version')}' is not semver")
    # 3/4. status/trigger (deferred = Tier-2 not-yet-active; allowed)
    if status not in ("primary", "conditional", "deferred"):
        card.errors.append(f"status '{status}' must be primary|conditional|deferred")
    # primary → trigger must be "always" (an explanatory "— ..." annotation is allowed)
    if status == "primary" and not str(trigger).strip().lower().startswith("always"):
        card.errors.append(f"primary agent must have trigger: always (got '{trigger}')")
    if status == "conditional" and (not trigger or trigger == "always"):
        card.errors.append("conditional agent needs a specific (non-'always') trigger")
    # 5/6. description
    desc = fm.get("description", "")
    if desc.startswith("I ") or desc.startswith("I'"):
        card.errors.append("description is first-person")
    if len(desc) > 512:
        card.errors.append(f"description {len(desc)} > 512 chars")
    # 11. deprecation
    if str(fm.get("deprecated", "false")).lower() == "true" and not fm.get("superseded_by"):
        card.errors.append("deprecated: true requires superseded_by")

    # ── Completeness — strict for primary, advisory otherwise ──
    for sec in REQUIRED_SECTIONS:
        if sec not in s:
            completeness.append(f"missing required section '## {sec}'")
    if active and "Position in Workflow" not in s:
        card.warnings.append("primary agent missing '## Position in Workflow'")
    h = s.get("Handoffs", "")
    for fld in ("Receives from", "Passes to", "Human gate"):
        if f"**{fld}**" not in h:
            completeness.append(f"Handoffs missing '**{fld}**'")
    if not re.search(r"^\s*-?\s*\[[ xX]\]", s.get("Evaluation Criteria", ""), re.M):
        completeness.append("Evaluation Criteria has no '[ ]' checklist item")

    # 8. tools pattern (soft — known exceptions like langgraph-checkpointer)
    tools = fm.get("tools", []) or []
    for t in tools:
        if not t.startswith("mcp-"):
            card.warnings.append(f"tool '{t}' does not match mcp-* (CARDS_SPEC rule 8)")
    # Tools section present if tools non-empty (#119 — known debt → warning)
    if tools and "Tools & MCP Servers" not in s:
        card.warnings.append("declares tools[] but has no '## Tools & MCP Servers' section (#119)")


# ── Generation helpers ───────────────────────────────────────────────────────

def _handoff_line(card: Card, label: str) -> str:
    m = re.search(rf"\*\*{re.escape(label)}\*\*:\s*(.*)", card.sections.get("Handoffs", ""))
    return m.group(1).strip() if m else ""


def _parse_table(text: str) -> list[list[str]]:
    rows = []
    for line in text.splitlines():
        line = line.strip()
        if not line.startswith("|"):
            continue
        cells = [c.strip() for c in line.strip("|").split("|")]
        if all(set(c) <= {"-", ":"} for c in cells if c):  # separator row
            continue
        rows.append(cells)
    return rows


def write(name: str, lines: list[str]) -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    (OUT_DIR / name).write_text(AUTOGEN + "\n".join(lines) + "\n")


def generate(cards: list[Card]) -> None:
    # Generated reference docs reflect ALL parseable cards (50), so the topology is
    # complete even while some cards still carry validation debt. --check gates.
    ok = [c for c in cards if c.name]

    # HANDOFFS.md
    lines = ["# Handoffs (generated)", "", "| Agent | Team | Receives from | Passes to | Human gate |", "|---|---|---|---|---|"]
    for c in ok:
        lines.append(f"| {c.name} | {c.team} | {_handoff_line(c,'Receives from')} | {_handoff_line(c,'Passes to')} | {_handoff_line(c,'Human gate')} |")
    write("HANDOFFS.md", lines)

    # CONTRACTS.md
    lines = ["# Inter-Agent Contracts (generated)", ""]
    for c in ok:
        lines.append(f"## {c.name}")
        for sec in ("Inputs", "Outputs / Artifacts"):
            lines.append(f"\n**{sec}**\n")
            t = c.sections.get(sec, "")
            lines.append(t if t.strip().startswith("|") else "_none_")
        lines.append("")
    write("CONTRACTS.md", lines)

    # INFRASTRUCTURE_REQUIREMENTS.md — tool -> agents
    tool_map: dict[str, list[str]] = {}
    for c in ok:
        for t in c.fm.get("tools", []) or []:
            tool_map.setdefault(t, []).append(c.name)
    lines = ["# Infrastructure Requirements (generated)", "", "| Tool / MCP server | Used by | Count |", "|---|---|---|"]
    for t in sorted(tool_map):
        lines.append(f"| `{t}` | {', '.join(sorted(tool_map[t]))} | {len(tool_map[t])} |")
    write("INFRASTRUCTURE_REQUIREMENTS.md", lines)

    # SKILLS_INVENTORY.md + CAPABILITY_MATRIX.md
    skill_map: dict[str, list[str]] = {}
    for c in ok:
        for sk in c.fm.get("skills", []) or []:
            skill_map.setdefault(sk, []).append(c.name)
    lines = ["# Skills Inventory (generated)", "", "| Skill | Agents | Count |", "|---|---|---|"]
    for sk in sorted(skill_map):
        lines.append(f"| `{sk}` | {', '.join(sorted(skill_map[sk]))} | {len(skill_map[sk])} |")
    write("SKILLS_INVENTORY.md", lines)

    all_skills = sorted(skill_map)
    lines = ["# Capability Matrix (generated)", "", "Agent x skill.", "",
             "| Agent | " + " | ".join(all_skills) + " |",
             "|---|" + "|".join(["---"] * len(all_skills)) + "|"]
    for c in ok:
        marks = ["✓" if sk in (c.fm.get("skills") or []) else "" for sk in all_skills]
        lines.append(f"| {c.name} | " + " | ".join(marks) + " |")
    write("CAPABILITY_MATRIX.md", lines)

    # GATES_INVENTORY.md — gate -> agents (from Human gate)
    gate_map: dict[str, list[str]] = {}
    for c in ok:
        hg = _handoff_line(c, "Human gate")
        for g in sorted(set(re.findall(r"Gate\s*(\d)", hg))):
            gate_map.setdefault(f"Gate {g}", []).append(c.name)
    lines = ["# Gate Inventory (generated)", "", "Derived from each card's Handoffs `Human gate` entry.", "",
             "| Gate | Agents | Count |", "|---|---|---|"]
    for g in sorted(gate_map):
        lines.append(f"| {g} | {', '.join(sorted(gate_map[g]))} | {len(gate_map[g])} |")
    write("GATES_INVENTORY.md", lines)

    # topology.mmd
    lines = ["%% AUTO-GENERATED — Mermaid handoff topology", "flowchart LR"]
    for c in ok:
        passes = _handoff_line(c, "Passes to")
        for target in re.findall(r"[A-Z][\w/ ]+?Agent|P\d Agent|Statistical Analyst|Report Agent", passes):
            tgt = target.strip().replace(" ", "_")
            lines.append(f"  {c.name.replace('-', '_')} --> {tgt}")
    write("topology.mmd", lines)


# ── Main ─────────────────────────────────────────────────────────────────────

def main(check_only: bool) -> int:
    cards = load_cards()
    for c in cards:
        validate(c)

    n_err = sum(len(c.errors) for c in cards)
    n_warn = sum(len(c.warnings) for c in cards)

    print(f"Validated {len(cards)} cards: {n_err} error(s), {n_warn} warning(s).")
    for c in cards:
        for e in c.errors:
            print(f"  ERROR  {c.team}/{c.name}: {e}")
    if not check_only:
        for c in cards:
            for w in c.warnings:
                print(f"  warn   {c.team}/{c.name}: {w}")

    if check_only:
        return 1 if n_err else 0

    # Default mode always (re)generates; --check is the gate. Card debt is reported
    # above but does not block regeneration of the reference docs.
    generate(cards)
    print(f"\nGenerated {len(list(OUT_DIR.glob('*')))} docs in agents/generated/.")
    if n_err:
        print(f"NOTE: {n_err} card validation error(s) remain — run --check; tracked separately.")
    return 0


if __name__ == "__main__":
    sys.exit(main(check_only="--check" in sys.argv))
