#!/bin/bash
# Prevent hand-edits to generated agent files in .claude/agents/
# (except README.md which is hand-maintained).
#
# Rationale: agent files are generated by sync-agents.sh; edits are lost on regenerate.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
DST="$REPO_ROOT/.claude/agents"

# Get staged agent files (exclude README.md)
STAGED_AGENTS=$(
  git diff --cached --name-only |
    grep "^.claude/agents/.*\.md$" |
    grep -v "^.claude/agents/README.md$" ||
    true
)

if [ -z "$STAGED_AGENTS" ]; then
  # No agent files staged; pass
  exit 0
fi

# Check each staged agent against what sync-agents.sh outputs
SYNC_OUTPUT=$("$REPO_ROOT/scripts/sync-agents.sh" 2>&1 | grep -oE '.claude/agents/[^ ]+' || true)

ILLEGAL_EDITS=0
for agent in $STAGED_AGENTS; do
  if ! echo "$SYNC_OUTPUT" | grep -qF "$agent"; then
    echo "ERROR: Agent file $agent is generated (edits will be lost); do not commit manually."
    echo "Instead, edit agents/ or upstream/ source and re-run: make sync-agents"
    ILLEGAL_EDITS=$((ILLEGAL_EDITS + 1))
  fi
done

exit $ILLEGAL_EDITS
